CREATE TABLE users (
	id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR(255) NOT NULL
);

CREATE TABLE accounts (
	id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_id BIGINT NOT NULL,
	balance NUMERIC(19, 2) NOT NULL DEFAULT 0,
	CONSTRAINT fk_accounts_user FOREIGN KEY (user_id) REFERENCES users (id),
	CONSTRAINT chk_accounts_balance_non_negative CHECK (balance >= 0)
);

CREATE TABLE transfers (
	id   BIGINT            GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	source_account_id      BIGINT NOT NULL,
	destination_account_id BIGINT NOT NULL, 
	amount                 NUMERIC(19,2) NOT NULL,
	created_at             TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	idempotency_key        VARCHAR(255) NOT NULL,
	CONSTRAINT fk_transfers_source      FOREIGN KEY (source_account_id) REFERENCES accounts (id),
	CONSTRAINT fk_transfers_destination FOREIGN KEY (destination_account_id) REFERENCES accounts (id),
	CONSTRAINT uq_transfers_idempotency_key UNIQUE (idempotency_key),
	CONSTRAINT chk_transfers_amount_positive CHECK (amount > 0),
	CONSTRAINT chk_transfers_different_accounts CHECK (source_account_id <> destination_account_id)
);

CREATE INDEX idx_transfers_source ON transfers (source_account_id);
CREATE INDEX idx_transfers_destination ON transfers (destination_account_id);

CREATE INDEX idx_accounts_user ON accounts (user_id); 